export default {
    createVoteSession: 'CREATE_VOTE_SESSION',
    voteSessionCreated: 'VOTE_SESSION_CREATED',
    participantJoinSignal: 'PARTICIPANT_JOIN_SIGNAL',
    participantLeaveSignal: 'PARTICIPANT_LEAVE_SIGNAL',
    participantVoteSignal: 'PARTICIPANT_VOTE_SIGNAL',
    signalRConnected: 'SIGNAL_R_CONNECTED',
    joinVoteSession: 'JOIN_VOTE_SESSION',
    voteSessionJoined: 'VOTE_SESSION_JOINED',
    leaveVoteSession: 'LEAVE_VOTE_SESSION',
    voteSessionLeft: 'VOTE_SESSION_LEFT',
    sessionKeyChanged: 'SESSION_KEY-CHANGED',
    displayNameChanged: 'DISPLAY_NAME_CHANGED',
    emailChanged: 'EMAIL_CHANGED',
    descriptionChanged: 'DESCRIPTION_CHANGED',
    canVoteChanged: 'CAN_VOTE_CHANGED',
    castVote: 'CAST_VOTE',
    voteCast: 'VOTE_CAST',
    apiError: 'API_ERROR',
    voteSessionOpenSignal: 'VOTE_SESSION_OPEN_SIGNAL',
    openVoteSession: 'OPEN_VOTE_SESSION',
    dismissNotification: 'DISMISS_NOTIFICATION',
    applicationNotification: 'APPLICATION_NOTIFICATION',
    randomNameGenerated: 'RANDOM_NAME_GENERATED',
};